[build-system]
requires = ["scikit-build-core", "pybind11"]
build-backend = "scikit_build_core.build"

[project]
name = "librenderer"
version = "0.0.1"
description = "C++ backend for renderer"
requires-python = ">=3.7"

[tool.scikit-build]
cmake.version = "CMakeLists.txt"
